---
title: "pet proj"
author: "cchel"
date: "2023-11-30"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(stringr)
```

```{r}
seattle <- read_delim("../final project/datasets/Seattle_Pet_Licenses.csv",
                      show_col_types = FALSE)
```

This shows that there is a problem with the dataset.

```{r}
problems(seattle)
head(seattle)
```

In row 23773, column 7, there must have been an encoding error.

```{r}
seattle[23773, 7] <- 98104

head(seattle)
```

Replacing the broken value with the actual zip code, sourced from the Excel CSV file.

```{r}
nyc <- read_delim("../final project/datasets/NYC_Dog_Licensing_Dataset_20231129.csv",
                  show_col_types = FALSE)
head(nyc)
tail(nyc)
```

The NYC data works fine

```{r}
seattle %>% 
  filter(Species != "Cat" & Species != "Dog")
```

Standardizing capitalization:

```{r}
seattle <- seattle %>% 
  mutate(`Animal's Name` = str_to_title(`Animal's Name`))

head(seattle)

nyc <- nyc %>% 
  mutate(AnimalName = str_to_title(AnimalName))

head(nyc)
```

```{r}
seattle <- seattle %>% 
  mutate(date = str_replace_all(seattle$`License Issue Date`,
                                c("January" = "01", "February" = "02", "March" = "03",
                                  "April" = "04", "May" = "05", "June" = "06",
                                  "July" = "07", "August" = "08", "September" = "09",
                                  "October" = "10", "November" = "11", "December" = "12"))) %>% 
  mutate(Date = mdy(date))

head(seattle)
```

```{r}
nyc <- nyc %>%
  mutate(date = mdy(LicenseIssuedDate))

head(nyc)
```

```{r}
seattle <- seattle %>%
  mutate(ZipCode = `ZIP Code`) %>% 
  mutate(Breed = `Primary Breed`) %>% 
  mutate(Name = `Animal's Name`) %>% 
  select(Date, ZipCode, Breed, Name)

head(seattle)
```

```{r}
nyc <- nyc %>%
  mutate(Date = date) %>% 
  mutate(Breed = BreedName) %>%
  mutate(Name = AnimalName) %>% 
  select(Date, ZipCode, Breed, Name)
head(nyc)
```

```{r}
seattle <- seattle %>% 
  tail(40000)

seattle

nyc <- nyc %>% 
  tail(40000)

nyc

names <- bind_rows(seattle, nyc)
names
```

New Categorical Variable: City

```{r}
names <- names %>% 
  mutate(City = ifelse(substr(ZipCode, 1, 1) == 1, "New York City", "Seattle"))

names
```

```{r}
names <- names %>%
  count(Name) %>%
  mutate(Total = n) %>% 
  select(Name, Total)

head(names)
```

```{r}
seattleCount <- seattle %>% 
  count(Name) %>% 
  mutate(Seattle = n) %>% 
  select(Name, Seattle)
head(seattleCount)
```

```{r}
nycCount <- nyc %>% 
  count(Name) %>% 
  mutate(NYC = n) %>%
  select(Name, NYC)
head(nycCount)

nycCount
```

```{r}
names <- left_join(names, seattleCount)

names <- left_join(names, nycCount)

names

names <- names %>% 
  mutate(Seattle = ifelse(is.na(Seattle), 0, Seattle))

names <- names %>% 
  mutate(NYC = ifelse(is.na(NYC), 0, NYC))

names <- names %>% 
  arrange(desc(Total)) %>% 
  filter(Name != "Unknown") %>% 
  filter(Name != "Name Not Provided") %>% 
  filter(Name != "None") %>% 
  filter(Name != "Name")

head(names)
```

New Categorical Variable:

```{r}
names <- names %>% 
  mutate(UniqueToSeattle = ifelse(Seattle / Total >= 0.7, TRUE, FALSE)) %>% 
  mutate(UniqueToNYC = ifelse(NYC / Total >= 0.7, TRUE, FALSE))

names
```
