---
title: "project proposal"
author: "cchel"
date: "2023-11-16"
output: html_document
---

# Data and Audience

## Target Audience

Our primary audience includes pet enthusiasts, aspiring pet owners, animal welfare advocates, city planners, and researchers keen on unraveling the dynamics of pet ownership in Seattle. Businesses catering to pet-related services and products may find this dataset invaluable for market analysis and strategy development. For the typical adult, there is little need to explain any of the variables. Aspects such as pet name, type of animal, breed, and zip code are all self-explanatory.

## Databases: Content and Background

–The [Seattle] (https://data.seattle.gov/Community/Seattle-Pet-Licenses/jguv-t9rb) dataset is a comprehensive compilation, featuring key details such as license issue dates, unique license numbers, the names of pets, their species, and primary and secondary breeds. Additionally, the dataset provides a geographic dimension with ZIP codes, allowing for a nuanced exploration of pet ownership trends throughout the city. This data is Collected by Department of Finance and Administrative Services, The City of Seattle, in order to provide demographic and information data to the general public. It is accessible through the city's official data portal, ensuring credibility and transparency. It’s available in the public domain and retrieved from Seattle Pet Licenses | City of Seattle Open Data portal. We believe this data is suitable for our purpose because being an official document, it’s credible. In addition, its comprehensiveness in including details such as breed will help us illustrate strong analytical points and patterns.

The [New York City Dog License] (https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp) dataset contains dog names, gender, birth year, and breeds. It was compiled by NYC’s department of mental health and hygiene, for the purpose of keeping track of dog licenses. This increases reliability because the information is coming from the original source. While NYC is not the main focus, it will be used as comparison for Seattle’s data, providing insightful differentiations in that aspect.

## Brief Background: Interest, What's Already Known, What Will Be Gained

–Brief Background:
Seattle, renowned for its diverse and pet-friendly community, cherishes the bond between residents and their furry companions. This dataset offers a snapshot of this connection, showcasing not just the variety of pets but also the neighborhoods where these connections thrive. As of October 12, 2023, the dataset captures the essence of Seattle's pet landscape.

Why It's Interesting:
Beyond its cultural significance, the dataset holds practical implications for urban planning, community engagement, and understanding the preferences of pet owners. The inclusion of license issue dates allows for a temporal analysis, potentially revealing trends and shifts in pet ownership dynamics over time.

Message to Audience, Storylines, and Questions

–Through these questions and storylines, we aim to provide a comprehensive understanding of Seattle's pet landscape and offer valuable insights for a range of audiences interested in the intersection of community, pets, and urban dynamics:

### Questions(choose):
#### Geographic Insights:
- How is the distribution of pet ownership across different ZIP codes in Seattle?
- Are there clusters of certain pet species or breeds in specific neighborhoods?
- What correlations exist between pet ownership patterns and urban development?
- How do these patterns compare to NYC, another large urban city?

#### Breed Popularity Trends:
- Which pet breeds are currently the most popular in Seattle?
- Are there emerging trends in pet preferences, and how have they evolved over time?
- Do certain breeds correlate with specific demographic or socioeconomic factors in the city?

#### Community Engagement:
- How does the presence of pets in a neighborhood correlate with community engagement?
- Are there associations between the number of pet licenses and the liveliness of local events or initiatives?
- Can the data provide insights into the social fabric influenced by pet ownership in Seattle?



# Technical Description

## Reading Data Methods:

_Seattle Pet Licenses_: This file is a .csv file, so we will manually import it into studio like we have done with datasets in class. 

_New York City Dog Licenses_: This file is also a .csv file, to be manually imported.

dplyr will suffice in processing these datasets.

## Data Processing:

For the Seattle Pet Licenses dataset, we will need to resize the data by -50%, so that it will contain 25k entries.

For the New York City Dog Licenses dataset, it will also need to be resized down to 25k from 500k. The columns for licensing dates, birth year, and gender will need to be removed.

## Major Libraries and Packages to be Used:

These are the visualization tools we will use to graphically display maps:

- Maps library: This is needed in order to create, adjust, and view regional maps.

- Natural World Library: This will be useful for making bigger adjustments to maps, and has more advanced features that will enhance the visuals of our final product.

## Questions That Will be Answered with Statistical Analysis & Machine Learning:

- What patterns emerge through years?
- Where do the biggest changes occur?
- How do these patterns associate with different geographic regions?
- How does _all_ of this compare with that of another city?

## Major Challenges Anticipated:

_Scope_: Since our focus is narrowing into Seattle pets specifically, it may be difficult to find resources that pertain to this very specific demographic. We will have to find a map that works for the purposes of displaying Seattle zip codes, which we predict may not be easy to source.

_Topic novelty_: Our topic is not a broad global issue like climate change or wage inequality. For this project, we will need to research background information before building our product. However, because of how pinpointed our topic area is, it may be hard to find information online about it.

_Compactness_: Our datasets have many variables that can be interacted with. We must decide which ones we want to emphasize, and how to display them in a way that conveys the message we want to tell. We must be careful with not presenting an immense amount of information that will overload the audience.
